# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce3b0767f32b54236c5fa913f880fbf917a8847b9e41634591a3035952bc4468efb8184096179a6ccb544b0d38112ca04dba2f5d6f5fa71dcdca0608499e3a21

test:
  secret_key_base: 38a02143462c40813d36d739227d579de4ee598fbf8d8ad3e5c734438b407e4aaecc31c351c90afa728b9c3828b0894073fb02241d2fc322c1497ffe3abed3ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
